server:
  port: 9500
logging:
  level:
    ROOT: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: db-service
          uri: lb://DB-SERVICE
          predicates:
            - Path=/db-service/**
          filters:
            - AuthenticationFilter
        - id: load-service
          uri: lb://LOAD-SERVICE
          predicates:
            - Path=/load-service/**
          filters:
            - AuthenticationFilter

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY